import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavbarFooterWrapper from "./components/shared/NavbarFooterWrapper";
import { CartProvider } from "./components/shared/cartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pulse_e-frontend",
  description: "Generated by create next app",
   icons: {
    icon: "/img/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  return (
    <html lang="en">
    
      
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NavbarFooterWrapper>
          {children}
        </NavbarFooterWrapper>
      </body> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
      <NavbarFooterWrapper>
          {children}
        </NavbarFooterWrapper>
        </CartProvider>
      </body>
      
    </html>
  );
}
